name: Java CI/CD for SQLite and Swing Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Zulu JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Install SQLite JDBC Driver
        run: |
          wget https://github.com/xerial/sqlite-jdbc/releases/download/3.42.0.0/sqlite-jdbc-3.42.0.0.jar
      - name: Install JUnit 5
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar -O junit-platform-console-standalone.jar
      - name: Debug: List Java files
        run: find src -name "*.java"
      - name: Check dependencies
        run: ls -l sqlite-jdbc-3.42.0.0.jar junit-platform-console-standalone.jar
      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -d bin -cp ".:sqlite-jdbc-3.42.0.0.jar:junit-platform-console-standalone.jar" $(find src -name "*.java") || { echo 'Compilation failed'; exit 1; }
      - name: Run tests
        run: |
          java -cp ".:bin:sqlite-jdbc-3.42.0.0.jar:junit-platform-console-standalone.jar" org.junit.platform.console.ConsoleLauncher --scan-classpath

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Zulu JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build and package the application
        run: |
          mkdir -p bin
          javac -d bin -cp ".:sqlite-jdbc-3.42.0.0.jar:junit-platform-console-standalone.jar" $(find src -name "*.java")
      - name: Create JAR package
        run: |
          jar -cvf my-app.jar -C bin/ .
      - name: Deploy to Server or Cloud
        run: |
          scp my-app.jar username@your-server:/path/to/deployment/folder
