name: Java CI/CD for SQLite and Swing Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... steps de build ...

  deploy:
    if: false  # Ajoutez cette ligne pour désactiver le déploiement
    needs: build
    runs-on: ubuntu-latest
    steps:
      # ... steps de déploiement ...