name: Java CI/CD for SQLite and Swing Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... steps de build ...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server or Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /path/to/deployment/folder
            ls -la
            rm -rf *
            cp /home/${USER}/my-app.jar .
            chmod +x my-app.jar
            ./my-app.jar &
        run: |
          echo "::add-mask::${{ secrets.SERVER_HOST }}"
          echo "::add-mask::${{ secrets.SERVER_USERNAME }}"
          echo "::add-mask::${{ secrets.SERVER_PRIVATE_KEY }}"